### ISSUE TITLE
大佬你好，快手还是要安全验证 怎么办？

### ISSUE THREAD

**Issue by 5wcx** [SMalls0098/video-tools#1]
你这个cookie还是没用

**Comment by SMalls0098** [comment]
没有用吗？我这两天有时间再看一下。我测试的时候可以用的。我后面再试试

**Comment by 5wcx** [comment]
嗯 没用了 好像过几天就失效了。你这个已经失效了。

**Comment by SMalls0098** [comment]
我自己测试还是可以的。不知道是不是我的ip问题

**Comment by SMalls0098** [comment]
应该是你服务器的请求太大，快手把IP封了

**Comment by 5wcx** [comment]
你写一个for循环 100次 刷新几下。就会获取不到了。有什么方法能主动获取到这个did呢 或者怎么跳过验证

**Comment by SMalls0098** [comment]
最好的技术只能通过逆向快手去找最新的sig了
