### ISSUE TITLE
快手：运行出现 undefined 

### ISSUE THREAD

**Issue by chenyRain** [smalls0098/video-tools#11]
![image](https://user-images.githubusercontent.com/24472819/85199115-bf1e1800-b31f-11ea-82ff-c7e91da8eb00.png)

**Comment by smalls0098** [comment]
你有问题可以加一下技术交流群，进群后可以@我直接跟我说 

这个问题是获取不到用户信息，我这两天修复一下到时候更新到1.2.1版本就可以了

**Comment by chenyRain** [comment]
> 你有问题可以加一下技术交流群，进群后可以@我直接跟我说
> 
> 这个问题是获取不到用户信息，我这两天修复一下到时候更新到1.2.1版本就可以了

作者，更新了吗
