### ISSUE TITLE
请问可以添加likee的去水印接口吗

### ISSUE THREAD

**Issue by xdhuangyandi** [smalls0098/video-tools#19]
https://likee.com/@223034114/video/6793715296194300582
https://likee.com/hashtag/BroomChallenge
万分感谢🙏

**Comment by smalls0098** [comment]
国内可以进行寻访吗

**Comment by xdhuangyandi** [comment]
需要挂vpn才可以访问

**Comment by smalls0098** [comment]
大概看了一下，可能需要分析app，软件我用模拟器安装，还要下载谷歌件套，所以需要过段时间再看看了
