### ISSUE TITLE
快手一直是失败：操作太快了，请稍微休息一下

### ISSUE THREAD

**Issue by xskit** [smalls0098/video-tools#20]
array(3) {
  ["result"]=>
  int(2)
  ["error_msg"]=>
  string(39) "操作太快了，请稍微休息一下"
  ["host-name"]=>
  string(40) "webservice-sc-rs230.idcyz.hb1.kwaidc.com"
}

**Comment by smalls0098** [comment]
你携带cookie信息看看

**Comment by smalls0098** [comment]
setCookie

**Comment by wf58585858** [comment]
两点：

1，你自带的那个快手的url，在发送请求时候 
走到 GuzzleHttp\Handler\__invoke 方法时 执行 curl_exec($easy->handle); 这句话整个程序生命周期就终止
在 index.php 注册的 register_shutdown_function 都没有走进去。nginx 和 apache 都有这个问题，php是 remi 的源 ，版本 php73

    register_shutdown_function(function($a){
        print_r(func_get_args());
    });

这是 nginx 的访问记录
192.168.0.105 - - [15/Aug/2020:11:10:04 +0800] "GET /index.php HTTP/1.1" 502 3693 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"


2，建议指明一下各个平台的视频地址在什么地方获取，每个平台给个有效的测试地址示例，很多人不知道一些平台的视频地址在哪里找，尤其是类似快手，抖音这样的APP端视频产品，比如我。

**Comment by smalls0098** [comment]
> 两点：
> 
> 1，你自带的那个快手的url，在发送请求时候
> 走到 GuzzleHttp\Handler__invoke 方法时 执行 curl_exec($easy->handle); 这句话整个程序生命周期就终止
> 在 index.php 注册的 register_shutdown_function 都没有走进去。nginx 和 apache 都有这个问题，php是 remi 的源 ，版本 php73
> 
> ```
> register_shutdown_function(function($a){
>     print_r(func_get_args());
> });
> ```
> 
> 这是 nginx 的访问记录
> 192.168.0.105 - - [15/Aug/2020:11:10:04 +0800] "GET /index.php HTTP/1.1" 502 3693 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
> 
> 2，建议指明一下各个平台的视频地址在什么地方获取，每个平台给个有效的测试地址示例，很多人不知道一些平台的视频地址在哪里找，尤其是类似快手，抖音这样的APP端视频产品，比如我。

第一个问题，如果获取到
快手一直是失败：操作太快了，请稍微休息一下
类似的问题整个请求函数是有执行过的，因为可以获取到response，上面的问题是因为官方给我们的提示，我原本有通过videoErrorException返回给你们了，其他问题你可以看一下是不是自己服务器宽带有问题，因为程序本身需要借助网络进行访问，看linux是不是有防火墙之类的
第二个问题
我composer包里面有写上，全部平台的链接，至于链接哪里获取的话，这个不用我多说了。链接这个东西是最基础，还要我教的话，那就没必要了。
