### ISSUE TITLE
皮皮搞笑视频提取错误

### ISSUE THREAD

**Issue by alxe-so-le** [smalls0098/video-tools#24]
文件： /smalls/video-tools/src/Logic/PiPiXiaLogic.php
错误方法 ：setContents()
错误原因： $this->post('',[],[]),第二个参数应该为数组，现在字符串
 /**
     * 公共POST方法
     * @param $url
     * @param $data
     * @param array $headers
     * @return mixed|string
     */
    public function post(string $url = '', array $data = [], array $headers = [])

**Comment by smalls0098** [comment]
你如果有时间的话可以提交一下pull requests，我这边这段时间没空有时间的话我周末会更新的
