### ISSUE TITLE
作者啊快手的不行了、

### ISSUE THREAD

**Issue by JasonSanYe** [SMalls0098/video-tools#4]

**Comment by SMalls0098** [comment]
快手的我后面再看看

**Comment by JasonSanYe** [comment]
> 快手的我后面再看看

**Comment by Azer90** [comment]
确实快手不行了

**Comment by SMalls0098** [comment]
快手的ip限制问题

**Comment by Johnwicke** [comment]
快手，我的可以

**Comment by SMalls0098** [comment]
量小，没被拉黑就可以。

**Comment by Azer90** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ming"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 下午2:52
收件人: "SMalls0098/video-tools"<video-tools@noreply.github.com&gt;; 
抄送: "666"<2168177860@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SMalls0098/video-tools] 作者啊快手的不行了、 (#4)





 
量小，没被拉黑就可以。

**Comment by Johnwicke** [comment]
微视的不行吧，你们可以？返回请求参数错误
$contents = $this->post('https://h5.qzone.qq.com/webapp/json/weishi/WSH5GetPlayPage?t=0.4185745904612037&g_tk=', [
            'feedid' => $match[1],
        ], [
            'User-Agent' => self::ANDROID_USER_AGENT
        ]);

上面这个url是根据什么来的啊，t应该是个动态值吧？

**Comment by Azer90** [comment]
???






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Johnwicke"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 下午3:25
收件人: "SMalls0098/video-tools"<video-tools@noreply.github.com&gt;; 
抄送: "666"<2168177860@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SMalls0098/video-tools] 作者啊快手的不行了、 (#4)





 
微视的不行吧，你们可以？返回请求参数错误
 $contents = $this-&gt;post('https://h5.qzone.qq.com/webapp/json/weishi/WSH5GetPlayPage?t=0.4185745904612037&amp;g_tk=', [
 'feedid' =&gt; $match[1],
 ], [
 'User-Agent' =&gt; self::ANDROID_USER_AGENT
 ]);
 
上面这个url是根据什么来的啊，t应该是个动态值吧？

**Comment by SMalls0098** [comment]
你可以根据我test.php里面的链接测试，如果还是不可以的话，那么就是更新过了。我6.9号更新一次数据

**Comment by Azer90** [comment]
@SMalls0098 作者好久在搞一些比较火的其他视频解析啊

**Comment by SMalls0098** [comment]
好的，我尽量。我自己项目也用这几个。
