### ISSUE TITLE
Notice: String offset cast occurred in /Users/sanye/Documents/web/project/test/vendor/smalls/video-tools/src/Logic/KuaiShouLogic.php on line 55

### ISSUE THREAD

**Issue by JasonSanYe** [smalls0098/video-tools#7]
新版本一直有语法错误

**Comment by JasonSanYe** [comment]
Notice: Undefined offset: 0 in /Users/sanye/Documents/web/project/test/vendor/smalls/video-tools/src/Tools/Base.php on line 37

**Comment by JasonSanYe** [comment]
PHP版本：7.4.6

**Comment by smalls0098** [comment]
我修复了，你提交的参数有问题才会这样。我现在判断了。而且我改成自己提交cookie信息。

**Comment by JasonSanYe** [comment]
现在就是 VideoManager::DouYin()->start($url); 这样不行、必须DouYin(['*'=>'*']) 这里传个数组呗。

**Comment by smalls0098** [comment]
感谢你的反馈，我这边已经修复了。现在应该不会出现什么大问题了，接下来我要多加几个视频平台了

**Comment by JasonSanYe** [comment]
哈哈厉害的、作者能不能弄个群呀、大家一起学习讨论

**Comment by JasonSanYe** [comment]
> 感谢你的反馈，我这边已经修复了。现在应该不会出现什么大问题了，接下来我要多加几个视频平台了

哈哈厉害的，作者能不能弄个群呀，大家一起学习讨论

**Comment by smalls0098** [comment]
已经弄了，看一下readme
