### ISSUE TITLE
快手 Undefined index: user

### ISSUE THREAD

**Issue by JasonSanYe** [smalls0098/video-tools#8]
然后我用新网页生成的cookie：did或报错   string(7043) "#0 /usr/local/var/web/project/jianzhi/vendor/smalls/video-tools/src/Tools/KuaiShou.php(29): Smalls\VideoTools\Logic\KuaiShouLogic->setContents()
#1 /usr/local/var/web/project/jianzhi/app/Tool/Watermark/BaseWatermark.php(42): Smalls\VideoTools\Tools\KuaiShou->start('https://v.kuais...')
#2 /usr/local/var/web/project/jianzhi/app/Http/Controllers/Api/V1/TestController.php(28): App\Tool\Watermark\BaseWatermark->parsing('https://v.kuais...')
#3 [internal function]: App\Http\Controllers\Api\V1\TestController->index()
#4 /usr/local/var/web/project/jianzhi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /usr/local/var/web/project/jianzhi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
#6 /usr/local/var/web/project/jianzhi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\V1\TestController), 'index')

**Comment by JasonSanYe** [comment]
did 要特殊处理嘛、还是复制快手PC生成的就行

**Comment by smalls0098** [comment]
你复制给我一下，我试试

**Comment by JasonSanYe** [comment]
登陆后的： did=web_a6a7e3e1a4014bc695f672424895d4b1; didv=1591109751000; clientid=3; client_key=65890b29; Hm_lvt_86a27b7db2c5c0ae37fee4a8a35033ee=1591109757,1591970427; kuaishou.live.bfb1s=9b8f70844293bed778aade6e0a8f9942; userId=51611533; userId=51611533; kuaishou.live.web_st=ChRrdWFpc2hvdS5saXZlLndlYi5zdBKgAaCjxgTeOKOKuBZb5DHiOZCRd47RetP6Uq7ja8Qc0K8YUzu_Dnd2zXqKdQxBk7WoqxC4hPA2XrlP9-gKRy0E7pJXWIVoNcoPLqHZ20r8XKIv-NW8dXdxmwAefMMQzOahP0M37oaBe5ryNzgZi84YdjOgyW-NBqbGSRqtr4yp7DONw_5N8SaKff4SUwt5iBh5K6h1rekzLxA7KnJNQXRFsroaEhq2DZZ7DUHSmXUzdRyAf3O3USIgqzysiMZcXUjuioTj7guBkES98eKxDNMXR44vGILtMMMoBTAB; kuaishou.live.web_ph=ea1aa21b1f3b1305776dd0eebc926ba94a3e

**Comment by JasonSanYe** [comment]
没登陆的： did=web_a6a7e3e1a4014bc695f672424895d4b1; didv=1591109751000; clientid=3; client_key=65890b29; Hm_lvt_86a27b7db2c5c0ae37fee4a8a35033ee=1591109757,1591970427; kuaishou.live.bfb1s=9b8f70844293bed778aade6e0a8f9942

**Comment by smalls0098** [comment]
新版我更新了，你再试试

**Comment by JasonSanYe** [comment]
好的、对了作者：1055772768 这个qq群吗找不到啊、
然后我刚刚试了一下 快手小程序 好像不会限IP、然后没有did需求、你可以参考一下

**Comment by smalls0098** [comment]
好的

**Comment by smalls0098** [comment]
群号我添加了
